{{ config(materialized='table')}}

{% set remove_list = ["allInPings",
"assistMePings",
"assists",
"baitPings",
"baronKills",
"basicPings",
"bountyLevel",
"champExperience",
"championName",
"championTransform",
"champLevel",
"commandPings",
"consumablesPurchased",
"damageDealtToBuildings",
"damageDealtToObjectives",
"damageDealtToTurrets",
"damageSelfMitigated",
"dangerPings",
"deaths",
"detectorWardsPlaced",
"doubleKills",
"dragonKills",
"eligibleForProgression",
"enemyMissingPings",
"enemyVisionPings",
"firstBloodAssist",
"firstBloodKill",
"firstTowerAssist",
"firstTowerKill",
"gameEndedInEarlySurrender",
"gameEndedInSurrender",
"getBackPings",
"goldEarned",
"goldSpent",
"holdPings",
"individualPosition",
"inhibitorKills",
"inhibitorsLost",
"inhibitorTakedowns",
"itemsPurchased",
"killingSprees",
"kills",
"lane",
"largestCriticalStrike",
"largestKillingSpree",
"largestMultiKill",
"last_update",
"longestTimeSpentLiving",
"magicDamageDealt",
"magicDamageDealtToChampions",
"magicDamageTaken",
"needVisionPings",
"neutralMinionsKilled",
"nexusKills",
"nexusLost",
"nexusTakedowns",
"objectivesStolen",
"objectivesStolenAssists",
"onMyWayPings",
"participantId",
"pentaKills",
"physicalDamageDealt",
"physicalDamageDealtToChampions",
"physicalDamageTaken",
"primaryStyle_0_id",
"primaryStyle_0_var1",
"primaryStyle_0_var2",
"primaryStyle_0_var3",
"primaryStyle_1_id",
"primaryStyle_1_var1",
"primaryStyle_1_var2",
"primaryStyle_1_var3",
"primaryStyle_2_id",
"primaryStyle_2_var1",
"primaryStyle_2_var2",
"primaryStyle_2_var3",
"primaryStyle_3_id",
"primaryStyle_3_var1",
"primaryStyle_3_var2",
"primaryStyle_3_var3",
"primaryStyle_id",
"profileIcon",
"pushPings",
"quadraKills",
"riotIdName",
"riotIdTagline",
"role",
"sightWardsBoughtInGame",
"spell1Casts",
"spell2Casts",
"spell3Casts",
"spell4Casts",
"statPerks_defense",
"statPerks_flex",
"statPerks_offense",
"subStyle_0_id",
"subStyle_0_var1",
"subStyle_0_var2",
"subStyle_0_var3",
"subStyle_1_id",
"subStyle_1_var1",
"subStyle_1_var2",
"subStyle_1_var3",
"subStyle_id",
"summoner1Casts",
"summoner1Id",
"summoner2Casts",
"summoner2Id",
"summonerLevel",
"summonerName",
"teamEarlySurrendered",
"teamId",
"teamPosition",
"timeCCingOthers",
"timePlayed",
"totalDamageDealt",
"totalDamageDealtToChampions",
"totalDamageShieldedOnTeammates",
"totalDamageTaken",
"totalHeal",
"totalHealsOnTeammates",
"totalMinionsKilled",
"totalTimeCCDealt",
"totalTimeSpentDead",
"totalUnitsHealed",
"tripleKills",
"trueDamageDealt",
"trueDamageDealtToChampions",
"trueDamageTaken",
"turretKills",
"turretsLost",
"turretTakedowns",
"unrealKills",
"visionClearedPings",
"visionScore",
"visionWardsBoughtInGame",
"wardsKilled",
"wardsPlaced",
"win"]
 %}

{% set exclude_list = ["championId","matchId"] %}

WITH temp_table AS (
    {{ dbt_utils.unpivot( 
    relation =  ref('stg_players_match'),
    cast_to = "int",
    exclude = exclude_list,
    remove = remove_list,
    field_name = "itemBuyOrder",
    value_name = "itemId"
    )}}
)
SELECT
    temp_table.matchId,
    match_league_points.tier,
    match_league_points.division,
    temp_table.championId,
    champion_info.id,
    champion_info.name AS champion_name,
    champion_info.title AS champion_title,
    champion_info.primary_class,
    champion_info.secondary_class,
    CAST(RIGHT(temp_table.itemBuyOrder,1) AS int) AS itemBuyOrder,
    temp_table.itemId,
    item_info.depth AS item_tier,
    item_info.name,
    item_info.itemIsTrinket,
    item_info.itemIsVision,
    item_info.itemIsBoots
FROM temp_table
LEFT JOIN {{ source("data_dragon", "item_info")}} AS item_info
ON item_info.id = temp_table.itemId
LEFT JOIN {{ source("data_dragon", "champion_info")}}  AS champion_info
ON champion_info.key = temp_table.championId
LEFT JOIN {{ ref("match_league_points")}} AS match_league_points
ON match_league_points.matchId = temp_table.matchId
ORDER BY  itemBuyOrder DESC